

// 変数numに文字列の１を代入
var num = "1";

try {
    // not演算子を使い、if文を実行させる
    if(num !== 1){
        throw '変数numには、数値の1を入れてください';
    } 
    var like = "好きな数字は、" + num + "です。";
    console.log( like );

// catchの引数に、 Errorオブジェクトとして" throw "で指定した値が渡されている
} catch(e) {
    console.log( "エラー：", e );
}


// 結果
エラー： 変数numには、数値の1を入れてください


// 解説
6行目のif文は、変数numが" 数値の１ "でないときに実行される処理である
throwにより、オリジナルに定義した例外処理が、意図的に実行されている

